version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - PUBLIC_SUPABASE_URL=${PUBLIC_SUPABASE_URL}
        - PUBLIC_SUPABASE_ANON_KEY=${PUBLIC_SUPABASE_ANON_KEY}
    env_file:
      - .env
    container_name: nova-erp
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - nova-network

  nginx:
    image: nginx:alpine
    container_name: nova-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/www:/var/www/html
    depends_on:
      - app
    networks:
      - nova-network

networks:
  nova-network:
    driver: bridge
