version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_SUPABASE_URL=${PUBLIC_SUPABASE_URL}
        - PUBLIC_SUPABASE_ANON_KEY=${PUBLIC_SUPABASE_ANON_KEY}
        - PRIVATE_SUPABASE_API_KEY=${PRIVATE_SUPABASE_API_KEY}
        - PRIVATE_SUPABASE_SERVICE_ROLE=${PRIVATE_SUPABASE_SERVICE_ROLE}
        - PUBLIC_DISCORD_URL=${PUBLIC_DISCORD_URL}
    environment:
      - NODE_ENV=production
      - DOMAIN=${DOMAIN}
      - PUBLIC_SUPABASE_URL=${PUBLIC_SUPABASE_URL}
      - PUBLIC_SUPABASE_ANON_KEY=${PUBLIC_SUPABASE_ANON_KEY}
      - PRIVATE_SUPABASE_API_KEY=${PRIVATE_SUPABASE_API_KEY}
      - PRIVATE_SUPABASE_SERVICE_ROLE=${PRIVATE_SUPABASE_SERVICE_ROLE}
      - PUBLIC_DISCORD_URL=${PUBLIC_DISCORD_URL}
      - PUBLIC_NONCE_MESSAGE=${PUBLIC_NONCE_MESSAGE}
    env_file:
      - /opt/nova-erp/secrets/.env
    container_name: nova-erp
    restart: unless-stopped
    networks:
      - nova-network

  nginx:
    image: nginx:alpine
    container_name: nova-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d.template:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - nova-network
    environment:
      - DOMAIN=${DOMAIN}
    command: /bin/sh -c "envsubst '\$DOMAIN' < /etc/nginx/conf.d.template/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  nova-network:
    driver: bridge
