version: '3.8'
services:
 app:
   build:
     context: .
     dockerfile: Dockerfile
     args:
       - PUBLIC_SUPABASE_URL=${PUBLIC_SUPABASE_URL}
       - PUBLIC_SUPABASE_ANON_KEY=${PUBLIC_SUPABASE_ANON_KEY}
       - PRIVATE_SUPABASE_API_KEY=${PRIVATE_SUPABASE_API_KEY}
       - PRIVATE_SUPABASE_JWT_SECRET=${PRIVATE_SUPABASE_JWT_SECRET}
       - PRIVATE_SUPABASE_SERVICE_ROLE=${PRIVATE_SUPABASE_SERVICE_ROLE}
   environment:
     - NODE_ENV=production
     - PUBLIC_SUPABASE_URL=${PUBLIC_SUPABASE_URL}
     - PUBLIC_SUPABASE_ANON_KEY=${PUBLIC_SUPABASE_ANON_KEY}
     - PRIVATE_SUPABASE_API_KEY=${PRIVATE_SUPABASE_API_KEY}
     - PRIVATE_SUPABASE_JWT_SECRET=${PRIVATE_SUPABASE_JWT_SECRET}
     - PRIVATE_SUPABASE_SERVICE_ROLE=${PRIVATE_SUPABASE_SERVICE_ROLE}
   env_file:
     - /opt/nova-erp/secrets/.env
   container_name: nova-erp
   restart: unless-stopped
   networks:
     - nova-network

 nginx:
   image: nginx:alpine
   container_name: nova-nginx
   restart: unless-stopped
   volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d:ro
     - /etc/letsencrypt:/etc/letsencrypt:ro
   ports:
     - "80:80"
     - "443:443"
   depends_on:
     - app
   networks:
     - nova-network

networks:
 nova-network:
   driver: bridge