name: Deploy via SSH

on:
  push:
    branches:
      - main  # Trigger this workflow only on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run SSH commands on the server to execute deployment.sh
      - name: Run deployment script on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}           # The IP or domain of your server
          username: ${{ secrets.SSH_USERNAME }}   # The SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}     # The private SSH key
          port: 22                                # Default SSH port
          script: |
            echo "Navigating to the project directory..."
            cd /var/www/nova-erp                  # Navigate to the deployment directory
            echo "Running deployment script..."
            bash deployment.sh                   # Execute your deployment script
